### PR TITLE
Fix Memorystream::read() to advance the stream position

### LINKED ISSUE #5: Memorystream::read() doesn't advance the stream position
If you change the `read_write_from_memorystream` test to write & read two different values instead of the same value, this bug can be reproduced. The current test case succeeds because it writes "5" twice, but instead of reading two separate "5"s it's just reading the first "5" twice.

Changing the test case to be this instead (where one value is "3", the other is "5") reproduces the bug:
```rust
#[test]
fn read_write_from_memorystream() {
    let valueA = 3.0;
    let valueB = 5.0;
    let mut stream = Memorystream::new().expect("Error");
    let mut writer = BinaryWriter::new(&mut stream);
    writer.write_f32(valueA).expect("Failed to write f32");
    writer.write_f32(valueB).expect("Failed to write f32");

    let mut reader = BinaryReader::new(&mut stream);
    reader.seek_to(0).expect("Failed to seek");
    let value = reader.read_f32().expect("Failed to read f32");
    assert_eq!(valueA, value);
    let value = reader.read_f32().expect("Failed to read f32");
    assert_eq!(valueB, value);
}
```
with this output:
```
---- read_write_from_memorystream stdout ----
thread 'read_write_from_memorystream' panicked at 'assertion failed: `(left == right)`
  left: `5.0`,
 right: `3.0`', tests\lib.rs:341:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Discovered this bug while testing my fix to #4. Will put up the PR for this fix first.

### PR DESCRIPTION
**Pull request by berserkguard**
This PR is to fix #5 - updated the unit test to expose the failure and fixed the offending code in Memorystream.

### CODE REVIEW

File: tests/lib.rs [hunk 1]
```diff
@@ -326,16 +326,17 @@ fn read_write_string() {
 
 #[test]
 fn read_write_from_memorystream() {
-    let temp = 5.0;
+    let valueA = 3.0;
+    let valueB = 5.0;
```
Comment (mathias234) [inline tests/lib.rs:330]: Please use snake_case on variables.

**Review by mathias234 — CHANGES_REQUESTED** [review]

File: tests/lib.rs (hunk 1 above)
Comment (mathias234) [reply tests/lib.rs:330]: Ill merge it in for now, but keep it in mind for in the future
